### ISSUE TITLE
Only "WixUI_Advanced" for all Users installs correct

### ISSUE THREAD

**Issue by ThomasWinkel** [nbelyh/VisioPanelAddinVSTO#12]
Starting point:
* Created two new Extended Visio Addin Projects:
    1. WixUI_Advanced
    2. WixUI_Minimal
* Both with option "Create new (sample) template and stencil file"
* Did not touch the other options, did not modify the projects.
* Build (Addin)
* Build (Setup)
* Removed all Addins from Visio (registered by build process)

Results:
* Installed WixUI_Advanced only for me: only Addin registered, Template and stencil file not
* Deinstalled
* Installed WixUI_Advanced for all Users: Addin registered, Template and stencil file registered -> Perfect
* Deinstalled
* Installed WixUI_Minimal: Nothing registered
* Deinstalled

Software versions:
* Visio 2019 Professional 64bit
* Visual Studio Community 2019 Version 16.8.4
* WiX Toolset v3.11.2
* Windows 10 Pro Version 10.0.18363 Build 18363

Meanwhile I also tested "WixUI_InstallDir".
-> Addin and Stencil / Template files are not registered.

**Comment by nbelyh** [comment]
@ThomasWinkel Verified at last 😄 
The per-user install problem with "Advanced" install is reproducible in Visio 2019 and later (in Plan 2 as well). 
In Visio 2010 and 2007 the per-user installation works fine (with the same installer). Not sure if it is possible to install per-user in 2019 at all. Maybe they just removed this possibility (per-user stencil install) at some point? May need to investigate. The per-user stencil registration is just ignored by Visio 2019.

Was able to reproduce the issue with "Minimal" and "InstallDir" - it's trying to install per-user. 
This one can be fixed by adding ```<Property Id="ALLUSERS" Value="1" />```, but will fix in the project

**Comment by nbelyh** [comment]
Changed ALLUSERS=1 <Property Id="ALLUSERS" Value="1" /> in template
https://github.com/nbelyh/VisioPanelAddinVSTO/commit/5cff9e9b7776c444dfedebd273aa0ca7ce8c2edd

**Comment by nbelyh** [comment]
Releasing as is, with the only fix to set ALLUSERS=1, with no changes to per-user installs in Visio 2019
