### ISSUE TITLE
Available creation only C# projects, but not VB.Net (28/05/2020)

### ISSUE THREAD

**Issue by crataegi** [nbelyh/VisioPanelAddinVSTO#5]
I use your wonderful add-in sometimes ago and create there projects in VB.Net. Thank you !
Just now i install your template to new PC and there i can find only C# project in start menu
![missed VB.Net project](https://i.ibb.co/k5ByYhj/Studio.png)
Now VB.Net projects don't supperted in your template or just missed ?

**Comment by nbelyh** [comment]
Will check 😄  There were no plans to dump VB.NET as of now. Thank you for the update.
It is Visual Studio 2019, right?

**Comment by crataegi** [comment]
Yes.
![](https://i.ibb.co/RPHTjk5/version.png)

**Comment by nbelyh** [comment]
Should be in #7
The fix available as pre-releases 1.2.2
@crataegi would be great if you could verify if it works properly.

I have checked with latest VS 2019 Community, now it shows up:
![](https://user-images.githubusercontent.com/528366/83340885-a650b280-a2dd-11ea-86eb-76f268ab81c8.png)

**Comment by crataegi** [comment]
I download and install new release 1.2.2.1522 ! After this i can create both type of projects: vb.net and c#. Thank you !
But in new solution all links are broken...
![broken links in solution](https://i.ibb.co/8rXJ5zP/wix.png)

**Comment by nbelyh** [comment]
@crataegi Thank you for verifying 😄 
Looks like a framework version mismatch. I have verified on clean machine with the latest VS2019.
Could you share the project, and VS version? Or just ping me directly so that we could check together with Teams in your environment to check what happenned! 
BTW could you try changing the target framework version in the project settings? Looks like the one selected by default not exist on your computer.

**Comment by nbelyh** [comment]
![image](https://user-images.githubusercontent.com/528366/83365788-15480d00-a3ab-11ea-85c4-9438bdd59e9c.png)

**Comment by nbelyh** [comment]
Probably need to test this scenario and verify that by default .net sdk framework version is selected that exists in the target VS installation.

**Comment by nbelyh** [comment]
@crataegi did you manage to fix the references issue with framework version change?
